### ISSUE TITLE
rework spell cast intent output

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#100]
it's okay how it is now, but it could be improved.

"<speak> druidcraft is a Transmutation cantrip.  *To cast, you need the following: Verbal, Somatic.* The spell duration is Instantaneous..."

The part in italics sounds off when you hear it out loud. I don't have a lot of great ideas on how to fix this. It can be left as-is if fixing this is too much work.

**Comment by Eldres** [comment]
*COMPLETED*
