### ISSUE TITLE
Clean up spells.json

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#112]
I'm noticing a lot of mistakes with our spells descriptions (and some of the other attributes). A lot of it stems from pulling the descriptions from a pdf, or other human error. Since we have people actually using this, we need to be more clean and organized with our data. 

This will be an ongoing task, and will take a long time to finish. Please occasionally spend time looking at a few spells to make sure the descriptions make sense and are grammatically correct, and make sense when spoken out loud, etc.

**Comment by Eldres** [comment]
As of December 28, this issue has been resolved. Most recent spells.js file in spell_class branch has been proof read and typos, spacing and grammar errors have been fixed.
