### ISSUE TITLE
Create Utterance Collision Tool

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#144]
With the addition of IndexIntent, we may begin running into a problem where the same utterance is used by two or more intents. For example:
> IndexIntent get information on {Index}
> SpellsIntent get information on {Spell}

This doesn't seem to have happened yet, but I don't have a quick way of checking. As we build out the utterances for IndexIntent it is very likely that we will introduce some collisions between intents. I think this is a great use case for your regex know-how.

**Comment by Eldres** [comment]
As long as we are mindful with our utterances, because we have the "LIST_OF_X" they shouldn't conflict with each other. Will need further testing to make sure this assumption is accurate.

**Comment by omegabytes** [comment]
I think you're correct about the slots precluding collisions. Since we haven't encountered any collisions over the past few releases, I'm going to mark this as resolved.
