### ISSUE TITLE
Metric Units Conversion for International Releases

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#147]
We are going live in the UK, but still have Imperial units from the US PHB. Attributes to change:

**items.js**
- capacity
- speed
- weight

**spells.js**
- range

**Comment by Eldres** [comment]
will have to check if she recognizes 'm' as 'meters' similar to how she recognizes 'ft' as feet

**Comment by Eldres** [comment]
*COMPLETED*

**Comment by Eldres** [comment]
*COMPLETED* seriously this time
