### ISSUE TITLE
Mapping for Alexa's speech recognizition

### ISSUE THREAD

**Issue by Eldres** [omegabytes/askTheDM#160]
Work on mapping for phrases so Alexa can better recognize them

ie:
"firebolt"{
"firevolt", "fireholt","fire bolt","firejolt", ...etc
}

**Comment by omegabytes** [comment]
This issue has more to do with how Amazon handles words _outside_ of our application. I did a bunch of research and contacted Amazon support - the long and the short is it's an Amazon issue. I added prompts in the skill description that ask users to open the application (interactive mode, not one shot mode) and retry if they're having issues.
