### ISSUE TITLE
Expand utterances

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#76]
@Eldres get with @jnoehren  on this.

**Comment by jnoehren** [comment]
NO we only minecraft now!

**Comment by omegabytes** [comment]
@jnoehren is this the site you used?
http://alexa-utter-gen.paperplane.io

**Comment by Eldres** [comment]
completed as of July 14th. Additional utterances can be added later as needed. Utter-gen worked like a charm
