### ISSUE TITLE
add "with advantage" and "with disadvantage" functionality

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/askTheDM#84]
*with advantage:*
- makes two dice rolls, takes the higher of the two
    - how does this mechanic work for multiple dice?

disadvantage is the opposite

**Comment by jnoehren** [comment]
JavaScript has a max and min function I think so we could just roll two dice and take the max or min. We could add disadvantage and advantage as attributes of dice roll

**Comment by omegabytes** [comment]
What if I'm rolling something crazy? Like, 10 d 6? Do I have advantage on all of the rolls?

**Comment by jnoehren** [comment]
Hmm I don't know if you have advantage on anything other than d20 rolls but there are times when the user will want to reroll damage dice

**Comment by jnoehren** [comment]
For that you would want to store each dice result in an array and when the user rerolls update the array

**Comment by jnoehren** [comment]
I think that means you'll need to save the array of dice as an attribute to the session and keep the session open and prompt the user for a reroll intent or a cancel

**Comment by omegabytes** [comment]
it is strictly d20 rolls, much simpler
